TPRental4You/Controllers/LocalizacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPRental4You.Data;
using TPRental4You.Migrations;
using TPRental4You.Models;

namespace TPRental4You.Controllers
{
    public class LocalizacoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LocalizacoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Localizacoes
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Localizacoes.Include(l => l.Veiculos).ToListAsync());
        }

        // GET: Localizacoes/Details/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Localizacoes == null)
            {
                return NotFound();
            }

            var localizacao = await _context.Localizacoes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (localizacao == null)
            {
                return NotFound();
            }

            return View(localizacao);
        }

        // GET: Localizacoes/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Localizacoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("Id,Tipo,Nome,InfoAdicional")] Localizacao localizacao)
        {

            ModelState.Remove(nameof(localizacao.Veiculos));
            if (ModelState.IsValid)
            {
                _context.Add(localizacao);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(localizacao);
        }

        // GET: Localizacoes/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Localizacoes == null)
            {
                return NotFound();
            }

            var localizacao = await _context.Localizacoes.FindAsync(id);
            if (localizacao == null)
            {
                return NotFound();
            }
            return View(localizacao);
        }

        // POST: Localizacoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tipo,Nome,InfoAdicional")] Localizacao localizacao)
        {
            if (id != localizacao.Id)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(localizacao.Veiculos));
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(localizacao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocalizacaoExists(localizacao.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(localizacao);
        }

        // GET: Localizacoes/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Localizacoes == null)
            {
                return NotFound();
            }

            var localizacao = await _context.Localizacoes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (localizacao == null)
            {
                return NotFound();
            }

            return View(localizacao);
        }

        // POST: Localizacoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Localizacoes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Localizacoes'  is null.");
            }
            var localizacao = await _context.Localizacoes.FindAsync(id);
            if (localizacao != null)
            {
                _context.Localizacoes.Remove(localizacao);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Administrador")]
        private bool LocalizacaoExists(int id)
        {
            return _context.Localizacoes.Any(e => e.Id == id);
        }
    }
}

TPRental4You/Controllers/LucrosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPRental4You.Data;
using TPRental4You.Models;
using TPRental4You.Models.ViewModels;

namespace TPRental4You.Controllers
{
    public class LucrosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public LucrosController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Lucro
        [Authorize(Roles = "Gestor,Administrador")]
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Gestor"))
            {
                float valor7Dias = 0;
                float valor30Dias = 0;
                float media30Dias = 0;
                List<float> listaMedia30Dias = new List();

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var user = await _userManager.FindByIdAsync(userId);
                if (user == null)
                {
                    return NotFound();
                }

                var empresa = await _context.Empresas.Include(e => e.Lucro).FirstOrDefaultAsync(m => m.Id == user.EmpresaId);

                foreach (var item in empresa.Lucro.ToList())
                {
                    if ((DateTime.Now - item.diaHora).TotalDays < 7)
                    {
                        valor7Dias += item.valor;
                    }

                    if ((DateTime.Now - item.diaHora).TotalDays < 30)
                    {
                        valor30Dias += item.valor;
                        listaMedia30Dias.Add(item.valor);
                    }
                }

                media30Dias = (float)Math.Round((listaMedia30Dias.Count() / 30.0), 2);

                LucroViewModel lucroViewModel = new LucroViewModel();

                lucroViewModel.Lucro7Dias = (float)Math.Round(valor7Dias,2);
                lucroViewModel.Lucro30Dias = (float)Math.Round(valor30Dias,2);
                lucroViewModel.MediaReservas30Dias = (float)Math.Round(media30Dias,2);

                //var applicationDbContext = _context.Lucro.Include(f => f.empresa);
                return View(lucroViewModel);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Gestor")]
        // POST: Cursos/GraficoVendas/5
        public async Task<IActionResult> GetDadosReservas()
        {
            //dados de exemplo
            List<object> dados = new List<object>();

            DataTable dt = new DataTable();
            dt.Columns.Add("Dias", System.Type.GetType("System.String"));
            dt.Columns.Add("Reservas", System.Type.GetType("System.Int32"));
            DataRow dr = dt.NewRow();

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresas.Include(e => e.Reservas).FirstOrDefaultAsync(m => m.Id == user.EmpresaId);

            /*foreach (var item in empresa.Lucro.ToList())
            {
                if ((DateTime.Now - item.diaHora).TotalDays < 30)
                {
                    dr["Dias"] = "Dia " + item.diaHora.Day;
                    dr["Lucro"] = item.valor;
                    dt.Rows.Add(dr);
                    dr = dt.NewRow();
                }
            }*/

            //correr 30 vezes
            for (int i = 0; i < 30; i++)
            {
                var count = 0;

                dr["Dias"] = "Dia " + (DateTime.Now.AddDays(-i).Day);

                //correr todas as reservas
                foreach (var item in empresa.Reservas.Where(r => (DateTime.Now.AddDays(-i).Day) == r.DataDeReserva.Day).ToList())
                {
                    count++;
                }
                dr["Reservas"] = count;
                dt.Rows.Add(dr);
                dr = dt.NewRow();
            }

            /*foreach (var item in empresa.Reservas.ToList())
            {
                if ((DateTime.Now - item.DataDeLevantamento).TotalDays < 30)
                {
                    dr["Dias"] = "Dia " + item.DataDeLevantamento.Day;
                    dr["Reservas"] = item.Preco;
                    dt.Rows.Add(dr);
                    dr = dt.NewRow();
                }
            }*/


            foreach (DataColumn dc in dt.Columns)
            {
                List<object> x = new List<object>();
                x = (from DataRow drr in dt.Rows select drr[dc.ColumnName]).ToList();
                dados.Add(x);
            }
            return Json(dados);

        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        // POST: Cursos/GraficoVendas/5
        public async Task<IActionResult> GetDadosReservasAdmin()
        {
            //dados de exemplo
            List<object> dados = new List<object>();

            DataTable dt = new DataTable();
            dt.Columns.Add("Dias", System.Type.GetType("System.String"));
            dt.Columns.Add("Reservas", System.Type.GetType("System.Int32"));
            DataRow dr = dt.NewRow();

            /*foreach (var item in empresa.Lucro.ToList())
            {
                if ((DateTime.Now - item.diaHora).TotalDays < 30)
                {
                    dr["Dias"] = "Dia " + item.diaHora.Day;
                    dr["Lucro"] = item.valor;
                    dt.Rows.Add(dr);
                    dr = dt.NewRow();
                }
            }*/

            //correr 30 vezes
            for (int i = 0; i < 30; i++)
            {
                var count = 0;

                dr["Dias"] = "Dia " + (DateTime.Now.AddDays(-i).Day);

                //correr todas as reservas
                foreach (var item in _context.Reservas.Where(r => (DateTime.Now.AddDays(-i).Day) == r.DataDeReserva.Day).ToList())
                {
                    count++;
                }
                dr["Reservas"] = count;
                dt.Rows.Add(dr);
                dr = dt.NewRow();
            }

            /*foreach (var item in empresa.Reservas.ToList())
            {
                if ((DateTime.Now - item.DataDeLevantamento).TotalDays < 30)
                {
                    dr["Dias"] = "Dia " + item.DataDeLevantamento.Day;
                    dr["Reservas"] = item.Preco;
                    dt.Rows.Add(dr);
                    dr = dt.NewRow();
                }
            }*/


            foreach (DataColumn dc in dt.Columns)
            {
                List<object> x = new List<object>();
                x = (from DataRow drr in dt.Rows select drr[dc.ColumnName]).ToList();
                dados.Add(x);
            }
            return Json(dados);

        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        // POST: Cursos/GraficoVendas/5
        public async Task<IActionResult> GetDadosReservas12Admin()
        {
            //dados de exemplo
            List<object> dados = new List<object>();

            DataTable dt = new DataTable();
            dt.Columns.Add("Mes", System.Type.GetType("System.String"));
            dt.Columns.Add("Reservas", System.Type.GetType("System.Int32"));
            DataRow dr = dt.NewRow();

            //correr 30 vezes
            for (int i = 0; i < 12; i++)
            {
                var count = 0;

                dr["Mes"] = "Mês " + (DateTime.Now.AddMonths(-i).Month);

                //correr todas as reservas
                foreach (var item in _context.Reservas.Where(r => (DateTime.Now.AddMonths(-i).Month) == r.DataDeReserva.Month).ToList())
                {
                    count++;
                }
                dr["Reservas"] = count;
                dt.Rows.Add(dr);
                dr = dt.NewRow();
            }

            foreach (DataColumn dc in dt.Columns)
            {
                List<object> x = new List<object>();
                x = (from DataRow drr in dt.Rows select drr[dc.ColumnName]).ToList();
                dados.Add(x);
            }
            return Json(dados);

        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        // POST: Cursos/GraficoVendas/5
        public async Task<IActionResult> GetDadosClientes12Admin()
        {
            //dados de exemplo
            List<object> dados = new List<object>();

            DataTable dt = new DataTable();
            dt.Columns.Add("Mes", System.Type.GetType("System.String"));
            dt.Columns.Add("Clientes", System.Type.GetType("System.Int32"));
            DataRow dr = dt.NewRow();

            var clientes = await _userManager.GetUsersInRoleAsync("Cliente");

            //correr 12 vezes
            for (int i = 0; i < 12; i++)
            {
                var count = 0;

                dr["Mes"] = "Mês " + (DateTime.Now.AddMonths(-i).Month);

                //correr todas as reservas
                foreach (var item in clientes.Where(u => (DateTime.Now.AddMonths(-i).Month) == u.DataDeRegisto.Month).ToList())
                {

                    count++;
                }
                dr["Clientes"] = count;
                dt.Rows.Add(dr);

TPRental4You/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rental4You</title>
    <link rel="icon" href="/imagens/meuautomovelmaresia1.png"
          type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/TPRental4You.styles.css" asp-append-version="true" />*@
   @* <link rel="stylesheet" href="~/css/carousel.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/css/MyStyleSheet.css" asp-append-version="true" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
          crossorigin="anonymous" />
    <link rel="stylesheet"
          href="style.css" />
    <link rel="preconnect"
          href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap"
          rel="stylesheet" />
</head>
<body >
    <div >
        <header >
            <div class="container" >
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark mb-3 fixed-top" style="background-color:cadetblue">
                    <div class="container">
                        <a class="navbar-brand text-light" asp-controller="Home" asp-action="Index"><strong>Rental4You</strong></a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">*@
                        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                            @*<ul class="navbar-nav flex-grow-1">*@
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                @if (!User.IsInRole("Administrador"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Reservas" asp-action="Index">Reservas</a>
                                    </li>
                                }
                                <!-- <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                    </li>-->
                                @if (User.IsInRole("Funcionario") || User.IsInRole("Gestor"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Veiculos" asp-action="Index">Veiculos</a>
                                    </li>
                                }

                                @if (User.IsInRole("Administrador"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Empresas" asp-action="Index">Empresas</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="TiposDeVeiculos" asp-action="Index">Categorias</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Localizacoes" asp-action="Index">Localizacoes</a>
                                    </li>
                                }

                                @if (User.IsInRole("Gestor") || User.IsInRole("Administrador"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Utilizadores" asp-action="Index">Utilizadores</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="Lucros" asp-action="Index">Painel de controlo</a>
                                    </li>
                                }
                            </ul>
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </div>
        </header>

        
       <!-- <main class="container-fluid" id="banner-containerTeste" style="background-image: url('imagens/bgimage.jpg'); background-repeat: no-repeat; background-size: cover;">

         </main>-->
        <main class="container mt-5 pt-5 text-start">
            @RenderBody()
         </main>
    
        
    </div>



    <!-- footer -->
    <section id="footer" >
        <section id="banner">
            <div class="container-fluid" id="banner-container" style="padding-bottom: 10px; padding-top: 30px;">
                <div class="row" id="banner-row">
                    <div class="col-md-12" id="footer-col1">

                        <h3>Rental4You</h3>

                        <p>
                            &copy; 2022 - Rental4You - Todos os direitos reservados.
                        </p>

                        <p id="ola"><a asp-area="" asp-controller="Home" asp-action="Privacy" class="btn btn-primary">Política de Privacidade</a></p>

                    </div>
                    
                </div>
            </div>
        </section>
    </section>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>