TPRental4You/Models/Reserva.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace TPRental4You.Models
{
    public enum estadoReserva
    {
        Por_Confirmar, Confirmada, Rejeitada, Finalizada, Cancelada
    }

    public enum situacaoReserva
    {
        Por_Pagar, Vencido, Cliente_Entregou, Reembolsado
    }
    public class Reserva
    {
        public int Id { get; set; }

        [Display(Name = "Estado da Reserva", Prompt = "Confirme a reserva")]
        //public estadoReserva? Confirmada { get; set; }
        public estadoReserva? EstadoReserva { get; set; }
        public float Preco { get; set; }
        public DateTime DataDeLevantamento { get; set; }
        public DateTime DataDeEntrega { get; set; }
        public DateTime DataDeReserva { get; set; }
        public string ClienteId { get; set; }
        public ApplicationUser cliente { get; set; }
        public int VeiculoId { get; set; }
        public Veiculo veiculo { get; set; }
        public int EmpresaId { get; set; }
        public Empresa empresa { get; set; }
        public ICollection<Estado> estados { get; set; }
        public situacaoReserva? Situacao { get; set; }
        [Range(0, 5, ErrorMessage = "Mínimo: 0 , máximo: 5")]
        public float? Classificacao { get; set; }
        public Lucro? Lucro { get; set; }
        public Avaliacao? Avaliacao { get; set; }
    }
}

TPRental4You/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.AccessControl;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPRental4You.Data;
using TPRental4You.Models;
using TPRental4You.Models.ViewModels;

namespace TPRental4You.Controllers
{
    public class ReservasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ReservasController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Reservas
        [Authorize(Roles = "Cliente,Funcionario, Gestor")]
        public async Task<IActionResult> Index([Bind("EstadoReserva,TiposDeVeiculoId,VeiculoId,ClienteId,DataDeLevantamento,DataDeEntrega")]
            PesquisaReservaViewModel? pesquisaReserva)
        {

            ViewData["TiposDeVeiculoId"] = new SelectList(_context.TiposDeVeiculos.ToList(), "Id", "Nome");
            ViewData["VeiculoId"] = new SelectList(_context.Veiculos.ToList(), "Id", "Matricula");
            var clientes = await _userManager.GetUsersInRoleAsync("Cliente");
            ViewData["ClienteId"] = new SelectList(clientes.ToList(), "Id", "Email");



            if (User.IsInRole("Administrador"))
            {
                var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados);
                return View(await applicationDbContext.ToListAsync());
            }
            else if (User.IsInRole("Funcionario") || User.IsInRole("Gestor"))
            {
                var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var userFuncionario = await _context.Users.Include(u => u.Empresa).Include(u => u.Reservas)
                    .FirstOrDefaultAsync(u => u.Id == id);

                if (pesquisaReserva.EstadoReserva != 0 && pesquisaReserva.TiposDeVeiculoId != 0 && pesquisaReserva.VeiculoId != 0
                    && pesquisaReserva.ClienteId != null && !pesquisaReserva.ClienteId.Equals("Cliente")
                    && !pesquisaReserva.DataDeLevantamento.ToString().Equals("01/01/0001 00:00:00") && !pesquisaReserva.DataDeEntrega.ToString().Equals("01/01/0001 00:00:00"))
                {

                    if (pesquisaReserva.EstadoReserva == 1)
                    {
                        var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                        Where(r => r.EmpresaId == userFuncionario.EmpresaId
                        && ((int?)r.EstadoReserva) == 0
                        && r.veiculo.TiposDeVeiculoId == pesquisaReserva.TiposDeVeiculoId
                        && r.VeiculoId == pesquisaReserva.VeiculoId
                        && r.ClienteId.Equals(pesquisaReserva.ClienteId)
                        && r.DataDeLevantamento.Day.Equals(pesquisaReserva.DataDeLevantamento.Day)
                        && r.DataDeEntrega.Day.Equals(pesquisaReserva.DataDeEntrega.Day));

                        return View(await applicationDbContext.ToListAsync());
                    }
                    else if (pesquisaReserva.EstadoReserva == 2)
                    {
                        var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                        Where(r => r.EmpresaId == userFuncionario.EmpresaId
                        && ((int?)r.EstadoReserva) == 1
                        && r.veiculo.TiposDeVeiculoId == pesquisaReserva.TiposDeVeiculoId
                        && r.VeiculoId == pesquisaReserva.VeiculoId
                        && r.ClienteId.Equals(pesquisaReserva.ClienteId)
                        && r.DataDeLevantamento.Day.Equals(pesquisaReserva.DataDeLevantamento.Day)
                        && r.DataDeEntrega.Day.Equals(pesquisaReserva.DataDeEntrega.Day));

                        return View(await applicationDbContext.ToListAsync());
                    }
                    else if (pesquisaReserva.EstadoReserva == 3)
                    {
                        var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                        Where(r => r.EmpresaId == userFuncionario.EmpresaId
                        && ((int?)r.EstadoReserva) == 2
                        && r.veiculo.TiposDeVeiculoId == pesquisaReserva.TiposDeVeiculoId
                        && r.VeiculoId == pesquisaReserva.VeiculoId
                        && r.ClienteId.Equals(pesquisaReserva.ClienteId)
                        && r.DataDeLevantamento.Day.Equals(pesquisaReserva.DataDeLevantamento.Day)
                        && r.DataDeEntrega.Day.Equals(pesquisaReserva.DataDeEntrega.Day));

                        return View(await applicationDbContext.ToListAsync());
                    }
                    else
                    {
                        var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                        Where(r => r.EmpresaId == userFuncionario.EmpresaId
                        && ((int?)r.EstadoReserva) == 3
                        && r.veiculo.TiposDeVeiculoId == pesquisaReserva.TiposDeVeiculoId
                        && r.VeiculoId == pesquisaReserva.VeiculoId
                        && r.ClienteId.Equals(pesquisaReserva.ClienteId)
                        && r.DataDeLevantamento.Day.Equals(pesquisaReserva.DataDeLevantamento.Day)
                        && r.DataDeEntrega.Day.Equals(pesquisaReserva.DataDeEntrega.Day));

                        return View(await applicationDbContext.ToListAsync());
                    }
                }
                else if (pesquisaReserva.EstadoReserva != 0)
                {
                    if (pesquisaReserva.EstadoReserva == 1)
                    {
                        var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                        Where(r => r.EmpresaId == userFuncionario.EmpresaId
                        && ((int?)r.EstadoReserva) == 0);

                        return View(await applicationDbContext.ToListAsync());
                    }
                    else if (pesquisaReserva.EstadoReserva == 2)
                    {
                        var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                        Where(r => r.EmpresaId == userFuncionario.EmpresaId
                        && ((int?)r.EstadoReserva) == 1);

                        return View(await applicationDbContext.ToListAsync());
                    }
                    else if (pesquisaReserva.EstadoReserva == 3)
                    {
                        var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                        Where(r => r.EmpresaId == userFuncionario.EmpresaId
                        && ((int?)r.EstadoReserva) == 2);

                        return View(await applicationDbContext.ToListAsync());
                    }
                    else
                    {
                        var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                        Where(r => r.EmpresaId == userFuncionario.EmpresaId
                        && ((int?)r.EstadoReserva) == 3);

                        return View(await applicationDbContext.ToListAsync());
                    }
                }
                else if (pesquisaReserva.TiposDeVeiculoId != 0)
                {
                    var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                    Where(r => r.EmpresaId == userFuncionario.EmpresaId
                    && r.veiculo.TiposDeVeiculoId == pesquisaReserva.TiposDeVeiculoId);

                    return View(await applicationDbContext.ToListAsync());

                }
                else if (pesquisaReserva.VeiculoId != 0)
                {
                    var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                    Where(r => r.EmpresaId == userFuncionario.EmpresaId
                    && r.VeiculoId == pesquisaReserva.VeiculoId);

                    return View(await applicationDbContext.ToListAsync());

                }
                else if (pesquisaReserva.ClienteId != null && !pesquisaReserva.ClienteId.Equals("Cliente"))
                {
                    var applicationDbContext = _context.Reservas.Include(r => r.cliente).Include(r => r.veiculo).Include(r => r.empresa).Include(r => r.estados).
                    Where(r => r.EmpresaId == userFuncionario.EmpresaId
                    && r.ClienteId.Equals(pesquisaReserva.ClienteId));

                    return View(await applicationDbContext.ToListAsync());

                }

TPRental4You/Views/Reservas/Create.cshtml
@model TPRental4You.Models.Reserva

@{
    ViewData["Title"] = "Create";
}

<h4>Confirme os dados da sua reserva</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <select style="display:none" asp-for="EstadoReserva" class="form-control" asp-items="Html.GetEnumSelectList<estadoReserva>()"></select>
            <input type="hidden" value="@Model.DataDeLevantamento" asp-for="DataDeLevantamento" />
            <input type="hidden" value="@Model.DataDeEntrega" asp-for="DataDeEntrega" />
            <input type="hidden" value="@Model.DataDeReserva" asp-for="DataDeReserva" />
            <input type="hidden" value="@Model.Preco" asp-for="Preco" />
            <select style="display:none" asp-for="Situacao" class="form-control" asp-items="Html.GetEnumSelectList<situacaoReserva>()"></select>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DataDeLevantamento" class="control-label"></label>
                <input asp-for="DataDeLevantamento" readonly disabled class="form-control" />
                <span asp-validation-for="DataDeLevantamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDeEntrega" class="control-label"></label>
                <input asp-for="DataDeEntrega" readonly disabled class="form-control" />
                <span asp-validation-for="DataDeEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="ClienteId" type="hidden" value="@Model.ClienteId" class="form-control" asp-items="ViewBag.ClienteId"></input>
            </div>
            <div class="form-group">
                <input asp-for="VeiculoId" type="hidden" value="@Model.VeiculoId" class="form-control" asp-items="ViewBag.VeiculoId"></input>
            </div>
            <div class="form-group">
                <input asp-for="EmpresaId" type="hidden" value="@Model.EmpresaId" class="form-control" asp-items="ViewBag.EmpresaId"></input>
            </div>

            <div class="form-group pt-4">
                <p class="alert alert-success">
                    Esta reserva tem um custo de  <b>@Model.Preco</b> Euros.
                </p>
            </div>
            <div class="form-group">
                <input type="submit" value="Reservar" class="btn btn-success" />
                <a class="btn btn-warning" asp-controller="Home" asp-action="Index">Cancelar pedido</a>
            </div>
            <div class="form-group">
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

TPRental4You/Views/Reservas/Delete.cshtml
@model TPRental4You.Models.Reserva

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reserva</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoReserva)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstadoReserva)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeLevantamento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDeLevantamento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeEntrega)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDeEntrega)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.cliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.cliente.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.veiculo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.veiculo.Id)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Remover" class="btn btn-outline-danger " />
        <a class="btn btn-outline-primary" asp-action="Index">Voltar</a>
    </form>
</div>

TPRental4You/Views/Reservas/Details.cshtml
@model TPRental4You.Models.Reserva

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Detalhes da Reserva</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoReserva)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstadoReserva)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Situacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Situacao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeLevantamento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDeLevantamento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeEntrega)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDeEntrega)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.veiculo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.veiculo.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.empresa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.empresa.Nome)
        <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class="col-sm-2">
                Danos
        </dt>
        @if(ViewBag.Ficheiros == null) {
            <dd class="col-sm-10">
                    Sem danos
            </dd>
        } else {

        <div class="row d-flex">
                @foreach (var file in ViewBag.Ficheiros)
                {
                <div class="col p-2 m-2" style="border-radius:10px;">
                    <img src="@file"
                     class="img-thumbnail"
                     style="max-width:150px; max-height:150px" />
                </div>
                }
        </div>
        }
    </dl>
</div>
<div>
    <a class="btn btn-outline-primary" asp-action="Index">Voltar às reservas</a>
</div>

TPRental4You/Views/Reservas/Devolucao.cshtml
@model TPRental4You.Models.Reserva

@{
    ViewData["Title"] = "Edit";
}

<h1>Devolução</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <select style="display:none" asp-for="EstadoReserva" class="form-control" asp-items="Html.GetEnumSelectList<estadoReserva>()"></select>
            <input type="hidden" asp-for="Preco" class="form-control" />
            <select style="display:none" asp-for="VeiculoId" asp-items="ViewBag.VeiculoId"></select>
            <select style="display:none" asp-for="ClienteId" asp-items="ViewBag.ClienteId"></select>
            <select style="display:none" asp-for="EmpresaId" asp-items="ViewBag.EmpresaId"></select>
            <input type="hidden" asp-for="DataDeEntrega" />
            <input type="hidden" asp-for="DataDeLevantamento" />
            <input type="hidden" asp-for="DataDeReserva" />
            <select style="display:none" asp-for="Situacao" class="form-control">
                <option selected value="3"></option>
            </select>

            <div class="form-group pt-4">
                <div class="alert alert-warning">
                    <p style="text-align:left"><b>Infelizmente a sua reserva foi cancelada</b></p>
                    <p style="text-align:left">Pedimos desculpa, pelo incómodo e vamos prosseguir com a sua devolução</p>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Confirmar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-primary" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

TPRental4You/Views/Reservas/Devolver.cshtml
@model TPRental4You.Models.Reserva

@{
    ViewData["Title"] = "Devolver";
}

<h1>Devolver</h1>

<h4>Classifique a sua reserva</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <select style="display:none" asp-for="EstadoReserva" class="form-control" asp-items="Html.GetEnumSelectList<estadoReserva>()"></select>
            <input type="hidden" asp-for="Preco" class="form-control" />
            <select style="display:none" asp-for="VeiculoId" asp-items="ViewBag.VeiculoId"></select>
            <select style="display:none" asp-for="ClienteId" asp-items="ViewBag.ClienteId"></select>
            <select style="display:none" asp-for="EmpresaId" asp-items="ViewBag.EmpresaId"></select>
            <input type="hidden" asp-for="DataDeEntrega" />
            <input type="hidden" asp-for="DataDeLevantamento" />
            <input type="hidden" asp-for="DataDeReserva" />
            <select style="display:none" asp-for="Situacao" class="form-control">
                <option selected value="2"></option>
            </select>

            <div class="form-group">
                <label asp-for="Classificacao" class="control-label"></label>
                <input type="number" min="0.0" max="5.0" asp-for="Classificacao" class="form-control" />
                <span asp-validation-for="Classificacao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Devolver Veiculo" class="btn btn-success" />
                <a class="btn btn-warning" asp-controller="Reservas" asp-action="Index">Voltar atrás</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

TPRental4You/Views/Reservas/Edit.cshtml
@model TPRental4You.Models.Reserva

@{
    ViewData["Title"] = "Edit";
}

@if (Enum.GetName(typeof(estadoReserva), Model.EstadoReserva).Equals("Confirmada") && Enum.GetName(typeof(situacaoReserva), Model.Situacao).Equals("Por_Pagar"))
{
    <h1>Confirme os dados da reserva</h1>
}
else if (Enum.GetName(typeof(estadoReserva), Model.EstadoReserva).Equals("Rejeitada") && Enum.GetName(typeof(situacaoReserva), Model.Situacao).Equals("Por_Pagar"))
{
    <h1>Confirme os dados da reserva</h1>
    <h4>Tem a certeza que deseja rejeitar a reserva?</h4>
}
else
{
    <h1>Edit</h1>
    <h4>Reserva</h4>
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Preco" class="form-control" />
            <select style="display:none" asp-for="VeiculoId" asp-items="ViewBag.VeiculoId"></select>
            <select style="display:none" asp-for="ClienteId" asp-items="ViewBag.ClienteId"></select>
            <select style="display:none" asp-for="EmpresaId" asp-items="ViewBag.EmpresaId"></select>
            <select asp-for="EstadoReserva" style="display:none" class="form-control" asp-items="Html.GetEnumSelectList<estadoReserva>()"></select>
            <input type="hidden" asp-for="DataDeEntrega" />
            <input type="hidden" asp-for="Situacao" />
            <input type="hidden" asp-for="DataDeLevantamento" />
            <input type="hidden" asp-for="DataDeReserva" />

            <div class="form-group">
                <label asp-for="EstadoReserva" class="control-label"></label>
                <select asp-for="EstadoReserva" class="form-control" disabled asp-items="Html.GetEnumSelectList<estadoReserva>()"></select>
                <span asp-validation-for="EstadoReserva" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDeLevantamento" class="control-label"></label>
                <input asp-for="DataDeLevantamento" disabled readonly class="form-control" />
                <span asp-validation-for="DataDeLevantamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDeEntrega" class="control-label"></label>
                <input asp-for="DataDeEntrega" disabled readonly class="form-control" />
                <span asp-validation-for="DataDeEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control" disabled readonly asp-items="ViewBag.ClienteId"></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VeiculoId" class="control-label"></label>
                <select asp-for="VeiculoId" class="form-control" disabled readonly asp-items="ViewBag.VeiculoId"></select>
                <span asp-validation-for="VeiculoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpresaId" class="control-label"></label>
                <select asp-for="EmpresaId" class="form-control" disabled readonly asp-items="ViewBag.EmpresaId"></select>
                <span asp-validation-for="EmpresaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" disabled readonly class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submeter" class="btn btn-primary" style="background-color:cadetblue; border-color:cadetblue; border-radius:15px" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-primary" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

TPRental4You/Views/Reservas/Pagar.cshtml
@model TPRental4You.Models.Reserva

@{
    ViewData["Title"] = "Edit";
}

<h1>Pagar</h1>

<h4>Prossiga com o pagamento da Reserva</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <select style="display:none" asp-for="EstadoReserva" class="form-control" asp-items="Html.GetEnumSelectList<estadoReserva>()"></select>
            <input type="hidden" asp-for="Preco" class="form-control" />
            <select style="display:none" asp-for="VeiculoId" asp-items="ViewBag.VeiculoId"></select>
            <select style="display:none" asp-for="ClienteId" asp-items="ViewBag.ClienteId"></select>
            <select style="display:none" asp-for="EmpresaId" asp-items="ViewBag.EmpresaId"></select>
            <input type="hidden" asp-for="DataDeEntrega" />
            <input type="hidden" asp-for="DataDeLevantamento" />
            <input type="hidden" asp-for="DataDeReserva" />
            <select style="display:none" asp-for="Situacao" class="form-control">
                <option selected value="1"></option>
            </select>

            <div class="form-group">
                <label asp-for="DataDeLevantamento" class="control-label"></label>
                <input asp-for="DataDeLevantamento" disabled readonly class="form-control" />
                <span asp-validation-for="DataDeLevantamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDeEntrega" class="control-label"></label>
                <input asp-for="DataDeEntrega" disabled readonly class="form-control" />
                <span asp-validation-for="DataDeEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VeiculoId" class="control-label"></label>
                <select asp-for="VeiculoId" class="form-control" disabled readonly asp-items="ViewBag.VeiculoId"></select>
                <span asp-validation-for="VeiculoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpresaId" class="control-label"></label>
                <select asp-for="EmpresaId" class="form-control" disabled readonly asp-items="ViewBag.EmpresaId"></select>
                <span asp-validation-for="EmpresaId" class="text-danger"></span>
            </div>
            <div class="form-group pt-4">
                <p class="alert alert-success">
                    Entidade  <b>12345</b>
                </p>
                <p class="alert alert-success">

                    Referência  <b id="ac"></b>
                </p>
                <p class="alert alert-success">
                    Montante  <b>@Model.Preco</b> Euros.
                </p>
            </div>
            <div class="form-group">
                <input type="submit" value="Pagar" class="btn btn-success" />
                <a class="btn btn-warning" asp-controller="Home" asp-action="Index">Cancelar pagamento</a>
            </div>
        </form>
    </div>
</div>

<script>
    window.onload = function () {
        var minm = 111111111;
        var maxm = 999999999;
        var down = document.getElementById('ac');
        down.innerHTML = Math.floor(Math
            .random() * (maxm - minm + 1)) + minm;
    }

</script>

<div>
    <a class="btn btn-outline-primary" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }