TPRental4You/Models/Veiculo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Linq;

namespace TPRental4You.Models
{
    public enum Marcas
    {
        Audi,
        BMW,
        Citroën,
        Ferrari,
        Fiat,
        Ford,
        Honda,
        Hyundai,
        Jaguar,
        Jeepe,
        Lamborghini,
        Mercedes,
        Opel,
        Peugeot,
        Porshe,
        Renault,
        Seat,
        Toyota,
        Volkswagen
    }

    public enum tipoMudancas
    {
        Manuais, Automáticas
    }

    public class Veiculo
    {
        public int Id { get; set; }
        [Display(Name = "Matricula", Prompt = "Introduza a matricula do carro")]
        public string Matricula { get; set; }

        [Display(Name = "Marca", Prompt = "Introduza a marca do carro")]
        public string Marca { get; set; }

        [Display(Name = "Nome", Prompt = "Introduza o nome do veiculo")]
        public string Nome { get; set; }

        [Display(Name = "Km", Prompt = "Introduza o numero de km do carro")]
        public float Km { get; set; }

        [Display(Name = "Preço", Prompt = "Introduza o preço por hora do veiculo")]
        public float Preco { get; set; }

        [Display(Name = "Carro ativo")]
        public bool Ativo { get; set; }

        //[Display(Name = "Descrição", Prompt = "Introduza a descrição do carro")]
        //public string Descricao { get; set; }

        [Display(Name = "Lugares", Prompt = "Introduza o numero de lugares do carro")]
        public int Lugares { get; set; }

        [Display(Name = "Malas", Prompt = "Introduza o numero de malas do carro")]
        public int Malas { get; set; }

        [Display(Name = "Mudanças", Prompt = "Introduza o tipo de mudanças do carro")]
        public string Mudancas { get; set; }
        public DateTime DataInicial { get; set; }
        public DateTime DataFim { get; set; }
        public int LocalizacaoId { get; set; }
        public Localizacao localizacao { get; set; }
        public int TiposDeVeiculoId { get; set; }
        public TiposDeVeiculo tiposDeVeiculo { get; set; }
        public int EmpresaId { get; set; }
        public Empresa empresa { get; set; }
        public ICollection<Reserva> Reservas { get; set; }
        //Foto
        public byte[]? Foto { get; set; }

        [NotMapped]
        public IFormFile? FotoFile { get; set; }
    }
}

TPRental4You/Controllers/VeiculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.OData.Edm;
using TPRental4You.Data;
using TPRental4You.Migrations;
using TPRental4You.Models;
using TPRental4You.Models.ViewModels;

namespace TPRental4You.Controllers
{
    public class VeiculosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VeiculosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Veiculos
        [Authorize(Roles = "Funcionario, Gestor")]
        public async Task<IActionResult> Index([Bind("TiposDeVeiculoId,Ativo,ordenarTipo,ordenarEstado")]
            PesquisaVeiculoViewModel? pesquisaVeiculo)
        {
            ViewData["TiposDeVeiculoId"] = new SelectList(_context.TiposDeVeiculos.ToList(), "Id", "Nome");

            bool estado;
            if (pesquisaVeiculo.Ativo == 1)
                estado = true;
            else /*if(pesquisaVeiculo.Ativo == 2)*/
                estado = false;

            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userFuncionario = await _context.Users.Include(u => u.Empresa).Include(u => u.Reservas)
                .FirstOrDefaultAsync(u => u.Id == id);

            if (pesquisaVeiculo.TiposDeVeiculoId != 0 && pesquisaVeiculo.Ativo != 0)
            {

                if (pesquisaVeiculo.ordenarTipo != 0)
                {
                    if (pesquisaVeiculo.ordenarTipo == 1)
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId
                        && v.Ativo == estado).OrderBy(v => v.TiposDeVeiculoId);
                        return View(await applicationDbContext.ToListAsync());

                    }
                    else
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId
                        && v.Ativo == estado).OrderByDescending(v => v.TiposDeVeiculoId);
                        return View(await applicationDbContext.ToListAsync());
                    }
                }
                else if (pesquisaVeiculo.ordenarEstado != 0)
                {
                    if (pesquisaVeiculo.ordenarEstado == 3)
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId
                        && v.Ativo == estado).OrderBy(v => v.Ativo);
                        return View(await applicationDbContext.ToListAsync());

                    }
                    else
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId
                        && v.Ativo == estado).OrderByDescending(v => v.Ativo);
                        return View(await applicationDbContext.ToListAsync());

                    }
                }
                else
                {

                    var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId
                        && v.Ativo == estado);
                    return View(await applicationDbContext.ToListAsync());
                }

            }
            else if (pesquisaVeiculo.TiposDeVeiculoId != 0)
            {
                if (pesquisaVeiculo.ordenarTipo != 0)
                {
                    if (pesquisaVeiculo.ordenarTipo == 1)
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId)
                        .OrderBy(v => v.TiposDeVeiculoId);
                        return View(await applicationDbContext.ToListAsync());

                    }
                    else
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId)
                        .OrderByDescending(v => v.TiposDeVeiculoId);
                        return View(await applicationDbContext.ToListAsync());
                    }
                }
                else if (pesquisaVeiculo.ordenarEstado != 0)
                {
                    if (pesquisaVeiculo.ordenarEstado == 3)
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId)
                        .OrderBy(v => v.Ativo);
                        return View(await applicationDbContext.ToListAsync());

                    }
                    else
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId)
                        .OrderByDescending(v => v.Ativo);
                        return View(await applicationDbContext.ToListAsync());

                    }
                }
                else
                {

                    var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.TiposDeVeiculoId == pesquisaVeiculo.TiposDeVeiculoId);
                    return View(await applicationDbContext.ToListAsync());
                }

            }
            else if (pesquisaVeiculo.Ativo != 0)
            {

                if (pesquisaVeiculo.ordenarTipo != 0)
                {
                    if (pesquisaVeiculo.ordenarTipo == 1)
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                        && v.Ativo == estado)
                        .OrderBy(v => v.TiposDeVeiculoId);
                        return View(await applicationDbContext.ToListAsync());

                    }
                    else
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                         && v.Ativo == estado)
                        .OrderByDescending(v => v.TiposDeVeiculoId);
                        return View(await applicationDbContext.ToListAsync());
                    }
                }
                else if (pesquisaVeiculo.ordenarEstado != 0)
                {
                    if (pesquisaVeiculo.ordenarEstado == 3)
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                         && v.Ativo == estado)
                        .OrderBy(v => v.Ativo);
                        return View(await applicationDbContext.ToListAsync());

                    }
                    else
                    {
                        var applicationDbContext = _context.Veiculos.Include(v => v.empresa).Include(v => v.localizacao).Include(v => v.tiposDeVeiculo).Include(v => v.Reservas)
                        .Where(v => v.EmpresaId == userFuncionario.EmpresaId
                         && v.Ativo == estado)

TPRental4You/Views/Veiculos/Create.cshtml
@model TPRental4You.Models.Veiculo

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Veiculo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <select asp-for="Marca" class="form-control" asp-items="Html.GetEnumSelectList<Marcas>()"></select>
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control"></input>
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-floating">
                <div>
                    <img id="MyFoto" class="img-thumbnail" src="~/imagens/carroDefault.png" style="width: 20%;" />
                </div>
                <div>
                    <div>
                        <label asp-for="FotoFile">Insira uma foto do carro:</label>
                        <input type="file" accept=".png,.jpg,.jpeg,image/png,image/jpeg"
                               asp-for="FotoFile" class="form-control"
                               onchange="document.getElementById('MyFoto').src = window.URL.createObjectURL(this.files[0])"
                               required />
                        <span asp-validation-for="FotoFile" class="text-danger"></span>
                    </div>
                </div>


                <div class="form-group">
                    <label asp-for="Km" class="control-label"></label>
                    <input asp-for="Km" class="form-control" />
                    <span asp-validation-for="Km" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Preço por Hora
                    <input asp-for="Preco" class="form-control" />
                    <span asp-validation-for="Preco" class="text-danger"></span>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                    </label>
                </div>
                <div class="form-group">
                    <label asp-for="Lugares" class="control-label"></label>
                    <input asp-for="Lugares" class="form-control" />
                    <span asp-validation-for="Lugares" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Malas" class="control-label"></label>
                    <input asp-for="Malas" class="form-control" />
                    <span asp-validation-for="Malas" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Mudancas" class="control-label"></label>
                    <select asp-for="Mudancas" class="form-control" asp-items="Html.GetEnumSelectList<tipoMudancas>()"></select>
                    <span asp-validation-for="Mudancas" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DataInicial" class="control-label"></label>
                    <input asp-for="DataInicial" type="datetime-local" id="theDateInicial" class="form-control" />
                    <span asp-validation-for="DataInicial" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DataFim" class="control-label"></label>
                    <input asp-for="DataFim" type="datetime-local" id="theDateFinal" class="form-control" />
                    <span asp-validation-for="DataFim" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LocalizacaoId" class="control-label"></label>
                    <select asp-for="LocalizacaoId" class="form-control" asp-items="ViewBag.LocalizacaoId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="TiposDeVeiculoId" class="control-label"></label>
                    <select asp-for="TiposDeVeiculoId" class="form-control" asp-items="ViewBag.TiposDeVeiculoId"></select>
                </div>
                <div class="form-group">
                    <select asp-for="EmpresaId" style="display:none" class="form-control" asp-items="ViewBag.EmpresaId"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Criar" class="btn btn-primary" style="background-color:cadetblue; border-color:cadetblue; border-radius:15px" />
                </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-info" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

    <script>
        var date = new Date();

        var day = date.getDate();
        var month = date.getMonth() + 1;
        var year = date.getFullYear();

        var horas = date.getHours();
        var minutos = date.getMinutes();

        if (month < 10) month = "0" + month;
        if (day < 10) day = "0" + day;

        var today = year + "-" + month + "-" + day + "T" + horas + ":" + minutos;

        document.getElementById('theDateInicial').min = today;
        document.getElementById('theDateInicial').value = today;
        document.getElementById('theDateFinal').min = today;
        document.getElementById('theDateFinal').value = today;
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js%22%3E</script>

TPRental4You/Views/Veiculos/Delete.cshtml
@model TPRental4You.Models.Veiculo

@{
    ViewData["Title"] = "Delete";
}

<h1>Remover</h1>

<h3>Tem a certeza que pretende remover o veiculo?</h3>
<div>
    <h4>Veiculo</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Km)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Km)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Lugares)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Lugares)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Malas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Malas)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mudancas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mudancas)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataInicial)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataInicial)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataFim)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.localizacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.localizacao.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tiposDeVeiculo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tiposDeVeiculo.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.empresa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.empresa.Id)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Remover" class="btn btn-outline-danger" /> 
        <a class="btn btn-outline-primary"  asp-action="Index">Voltar</a>
    </form>
</div>

TPRental4You/Views/Veiculos/Details.cshtml
@model TPRental4You.Models.Veiculo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Veiculo</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class="col-sm-10">
            <img id="MyFoto" class="img-thumbnail" style="height:75px;width:auto"
                 src="data:image/*;base64,@(Convert.ToBase64String(Model.Foto))" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Km)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Km)
        </dd>
        <dt class="col-sm-2">
            Preço por hora
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Lugares)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Lugares)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Malas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Malas)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mudancas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mudancas)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataInicial)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataInicial)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataFim)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.localizacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.localizacao.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.tiposDeVeiculo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.tiposDeVeiculo.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.empresa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.empresa.Id)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("Funcionario") || User.IsInRole("Gestor"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-outline-warning">Editar</a>
        <a asp-action="Index" class="btn btn-outline-info">Voltar à lista</a>
    } else {
        <a asp-action="Index" asp-controller="Home" class="btn btn-outline-info">Voltar</a>
    }
</div>

TPRental4You/Views/Veiculos/Search.cshtml
@using TPRental4You.Models.ViewModels
@model PesquisaVeiculoViewModel

@{
    // Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h2>Filtrar por</h2>

<form method="post" action="Search">

    <!--<input type="text" id="VeiculoAPesquisar" name="VeiculoAPesquisar"
           placeholder="texto a procurar" />-->


    <select name="TiposDeVeiculoId" asp-items="ViewBag.TiposDeVeiculoId">
        <option id="defaultTipo" selected="selected">Veiculo</option>
    </select>
    <select name="EmpresaId" asp-items="ViewBag.EmpresaId">
        <option id="defaultEmpresas" selected="selected">Empresa</option>
    </select>


    <input name="LocalizacaoId" type="hidden" value="@Model.LocalizacaoId" asp-items="ViewBag.LocalizacaoId"></input>

    <input asp-for="@Model.DataPesquisaInicial" type="hidden" class="form-control" />
    <input asp-for="@Model.DataPesquisaFinal" type="hidden" class="form-control" />

    <button id="botaoPesquisa" type="submit" value="0" class="btn btn-default">
        🔍
    </button>


    <input id="ordenarCrescente" name="ordenarPreco" value="1" type="checkbox" onchange="cbChange(this)" class="ab">Preco mais baixo</input>
    <input id="ordenarDecrescente" name="ordenarPreco" value="2" type="checkbox" onchange="cbChange2(this)" class="ba">Preco mais alto</input>

    <input id="ordenarCrescenteEmpresa" name="ordenarClassificacao" value="3" type="checkbox" onchange="cbChange3(this)" class="bc">Classificacao mais baixo</input>
    <input id="ordenarDecrescenteEmpresa" name="ordenarClassificacao" value="4" type="checkbox" onchange="cbChange4(this)" class="cb">Classificacao mais alta</input>

</form>

<script>
    function cbChange(obj) {
        var cbs = document.getElementsByClassName("ba");
        cbs[0].checked = false;
    }

    function cbChange2(obj) {
        var cbs = document.getElementsByClassName("ab");
        cbs[0].checked = false;
    }
    function cbChange3(obj) {
        var cbs = document.getElementsByClassName("cb");
        cbs[0].checked = false;
    }
    function cbChange4(obj) {
        var cbs = document.getElementsByClassName("bc");
        cbs[0].checked = false;
    }
</script>

<h1>
    @ViewData["Title"]
</h1>

<div class="container bg-white">
    @if (Model.NumResultados == 0)
    {
        <p class="alert alert-warning">
            Não foi possível encontrar veiculos com os dados introduzidos. Por favor, reveja a sua
            pesquisa
        </p>
    }
    else
    {
        <p>Existe(m) @Model.NumResultados veiculo(s) disponiveis</p>
    }

    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        @foreach (var item in Model.ListaDeVeiculos)
        {
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">

                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">
                            @Html.DisplayFor(modelItem => item.Marca)
                            @Html.DisplayFor(modelItem => item.Nome)
                            (@Html.DisplayFor(modelItem => item.tiposDeVeiculo.Nome))
                        </h4>
                    </div>

                    <div class="card-body">

                        <img id="MyFoto" class="img-thumbnail" style="height:100px;width:auto"
                         src="data:image/*;base64,@(Convert.ToBase64String(item.Foto))" />

                        <h2 class="card-title pricing-card-title">
                            @Html.DisplayFor(modelItem => item.empresa.Nome)
                            (@Html.DisplayFor(modelItem => item.empresa.Avaliacao)☆)
                            <small class="text-muted fw-light"></small>
                        </h2>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="my-0 fw-normal">
                                @Html.DisplayFor(modelItem => item.Preco) €
                            </li>
                        </ul>
                        <a class="btn btn-lg btn-outline-primary"
                       asp-controller="Veiculos" asp-action="Details" asp-route-id="@item.Id">
                            Saber
                            mais
                        </a>
                        <a class="btn btn-lg btn-success"
                       asp-controller="Reservas" asp-action="Create" asp-route-id="@item.Id" asp-route-dataPesquisaInicial="@Model.DataPesquisaInicial" asp-route-dataPesquisaFinal="@Model.DataPesquisaFinal">
                            Reservar
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>